server:
  port: 8080
  servlet:
    context-path: /broker-payment

custom:
  email: ${EMAIL}
  password: ${EMAIL_PASSWORD}
  url: ${APPLICATION_URL}
  aws_expiration: ${AWS_FILE_LINK_EXPIRATION}

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
spring:

  datasource:
    url: ${DB_URL}/payment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match:
    - /**/v1/**/
    - /auth/**
    - /user/**
    - /api/records/**
    - /api/files/**
    - /api/admin/**
logging:
  level:
    com:
      application=INFO:
      org.hibernate.SQL: OFF
      org.hibernate.type.descriptor.sql.BasicBinder: OFF